version: "3.9"

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - apinet

  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - gerenciamento
    networks:
      - apinet

  atividades:
    build: ./atividades
    container_name: atividades
    ports:
      - "5002:5002"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - gerenciamento
      - reservas
    networks:
      - apinet

networks:
  apinet:
    driver: bridge